apiVersion : apps/v1
kind: Deployment
metadata:
  name: app1nginxaks 
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1nginxaks
  template:
    metadata:
      labels:
        app: app1nginxaks 
    spec:
      containers:
        - name: app1nginxaks 
          image: aksdevopsacr.azurecr.io/app1nginxaks
          imagePullPolicy: Always
          ports:
          - containerPort: 80